spring:
  profiles:
    active: postgre
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile:
        - oracle
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
    password: oracle
---
spring:
  config:
    activate:
      on-profile:
        - mariadb
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/foo
    username: user
    password: password
---
spring:
  config:
    activate:
      on-profile:
        - mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foo
    username: user
    password: password
---
spring:
  config:
    activate:
      on-profile:
        - postgre
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/foo
    username: user
    password: password

